# Generated by Django 5.1.1 on 2024-11-22 22:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_update_ruts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='rut',
            field=models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='Formato de RUT inválido. Debe ser como "12345678-9"', regex='^\\d{7,8}-[\\dkK]$')]),
        ),
    ]
