# Generated by Django 5.1.1 on 2024-11-29 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_doctor_especialidad'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipodiagnostico',
            options={},
        ),
        migrations.AlterField(
            model_name='doctor',
            name='especialidad',
            field=models.CharField(choices=[('traumatologia', 'Traumatología'), ('cardiovascular', 'Cirugía Cardiovascular')], default='traumatologia', max_length=20),
        ),
        migrations.AlterField(
            model_name='tipodiagnostico',
            name='especialidad',
            field=models.CharField(choices=[('traumatologia', 'Traumatología'), ('cardiovascular', 'Cirugía Cardiovascular')], default='traumatologia', max_length=20),
        ),
    ]
