# Generated by Django 5.1.1 on 2024-11-29 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_tipodiagnostico_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='genero',
            field=models.CharField(choices=[('', 'Seleccione...'), ('M', 'Masculino'), ('F', 'Femenino')], max_length=1),
        ),
    ]
