# Generated by Django 5.1.1 on 2024-11-30 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_paciente_genero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='especialidad',
            field=models.CharField(choices=[('traumatologia', 'Traumatologia'), ('cardiovascular', 'Cirugia Cardiovascular')], default='traumatologia', max_length=20),
        ),
        migrations.AlterField(
            model_name='tipodiagnostico',
            name='especialidad',
            field=models.CharField(choices=[('traumatologia', 'Traumatologia'), ('cardiovascular', 'Cirugia Cardiovascular')], default='traumatologia', max_length=20),
        ),
    ]
